DROP SCHEMA NOTESGESTOR;
CREATE SCHEMA IF NOT EXISTS NOTESGESTOR;
USE NOTESGESTOR;
CREATE TABLE IF NOT EXISTS USUARIS (
	ID INT PRIMARY KEY auto_increment,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NOM_COMPLET VARCHAR(60),
    IMAGE BLOB
);
CREATE TABLE IF NOT EXISTS CURSOS (
	ID INT PRIMARY KEY auto_increment,
    NOM VARCHAR(35) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTS (
	ID INT PRIMARY KEY auto_increment,
    NOM VARCHAR(35) NOT NULL UNIQUE
);
INSERT IGNORE INTO DEPARTAMENTS (NOM) VALUES ("Informatica");
INSERT IGNORE INTO DEPARTAMENTS (NOM) VALUES ("Jardineria");

CREATE TABLE IF NOT EXISTS ALUMNES (
	USUARI INT primary key,
    REPETIDOR BIT DEFAULT 0,
    CURS INT NOT NULL,
	FOREIGN KEY (CURS) REFERENCES CURSOS(ID),
	FOREIGN KEY (USUARI) REFERENCES USUARIS(ID)
);

CREATE TABLE IF NOT EXISTS PROFESORS (
	USUARI INT PRIMARY KEY,
    DEPARTAMENT INT NOT NULL, -- POSIBLE RELACION
    FOREIGN KEY (DEPARTAMENT) REFERENCES DEPARTAMENTS(ID)
);

CREATE TABLE IF NOT EXISTS ASIGNATURES (
	ID INT PRIMARY KEY auto_increment,
	CODI VARCHAR(3),
    NOM VARCHAR(50),
    CURS INT,
    FOREIGN KEY (CURS) REFERENCES CURSOS(ID),
    CONSTRAINT ONE_CODI_NOM_CURS UNIQUE(CODI,CURS)
);


CREATE TABLE IF NOT EXISTS DOCENCIA (
	ID INT PRIMARY KEY auto_increment, -- Se podria poner una pk en profe-alumne-asignatura 
    PROFESOR INT NOT NULL,
    ALUMNE INT NOT NULL,
    ASIGNATURA INT NOT NULL,
    FOREIGN KEY (PROFESOR) REFERENCES PROFESORS(USUARI),
    FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURES(ID),
    FOREIGN KEY (ALUMNE) REFERENCES ALUMNES(USUARI),
    CONSTRAINT ONE_PROFE_TO_ONE_ALUMNE UNIQUE(PROFESOR,ALUMNE,ASIGNATURA)
);
CREATE TABLE IF NOT EXISTS MISSATGES (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MISSATGE TEXT,
    PROFESOR INT NOT NULL,
    ALUMNE INT NOT NULL,
    FOTO TEXT,
	FOREIGN KEY (PROFESOR) REFERENCES PROFESORS(USUARI),
    FOREIGN KEY (ALUMNE) REFERENCES ALUMNES(USUARI)
);
INSERT IGNORE INTO CURSOS (NOM) VALUES ("2n DAM");
INSERT IGNORE INTO CURSOS (NOM) VALUES ("1r DAM");
INSERT IGNORE INTO DEPARTAMENTS (NOM) VALUES ("Informatica");
INSERT IGNORE INTO DEPARTAMENTS (NOM) VALUES ("Jardineria");
INSERT IGNORE INTO USUARIS (USERNAME,PASSWORD, NOM_COMPLET) VALUES ("Pep","Una contraseña","Pepe Alcazares");
INSERT IGNORE INTO USUARIS (USERNAME,PASSWORD, NOM_COMPLET) VALUES ("CatReg","aaa","Joan Ciscar");
INSERT IGNORE INTO USUARIS (USERNAME,PASSWORD, NOM_COMPLET) VALUES ("Juli","SOyu guapisimo","Juliano cesar");
INSERT IGNORE INTO USUARIS (USERNAME,PASSWORD, NOM_COMPLET) VALUES ("Javi","U","Javi De Olmo");
INSERT IGNORE INTO USUARIS (USERNAME,PASSWORD, NOM_COMPLET) VALUES ("Pepet","Ale","Super Pep");
INSERT IGNORE INTO USUARIS (USERNAME,PASSWORD, NOM_COMPLET) VALUES ("Un usuario mas","user","Usuario");
INSERT IGNORE INTO PROFESORS (USUARI,DEPARTAMENT) VALUES (1,1);
INSERT IGNORE INTO PROFESORS (USUARI,DEPARTAMENT) VALUES (3,1);
INSERT IGNORE INTO ALUMNES (USUARI,REPETIDOR,CURS) VALUES (2,1,1);
INSERT IGNORE INTO ASIGNATURES (CODI,NOM,CURS) VALUES ("PRG","Programacio",2);
INSERT IGNORE INTO ASIGNATURES (CODI,NOM,CURS) VALUES ("DI","Diseño de interfaces",1);
INSERT IGNORE INTO ASIGNATURES (CODI,NOM,CURS) VALUES ("SGE","Sistemas de gestion empresarial",1);
INSERT IGNORE INTO ASIGNATURES (CODI,NOM,CURS) VALUES ("BBDD","Base de datos",2);
INSERT IGNORE INTO ALUMNES (USUARI,REPETIDOR,CURS) VALUES (4,0,1);
INSERT IGNORE INTO ALUMNES (USUARI,REPETIDOR,CURS) VALUES (5,0,1);
INSERT IGNORE INTO ALUMNES (USUARI,REPETIDOR,CURS) VALUES (6,0,1);
INSERT IGNORE INTO DOCENCIA (PROFESOR,ALUMNE,ASIGNATURA) VALUES (1,2,1);
INSERT IGNORE INTO MISSATGES (MISSATGE,PROFESOR,ALUMNE) VALUES ("Hola tio com es fa el APAC 3?",1,2);